### ISSUE TITLE
incorrect pal maps path

### ISSUE THREAD

**Issue by david-wb** [pal-robotics/pmb2_navigation#4]
Pal maps appear to be at `/opt/ros/humble/share/pal_maps/maps/` and not `/opt/ros/humble/share/pal_maps/configurations.`

#3 Address this bug.

```
$ ls /opt/ros/humble/share/pal_maps/maps/
namo  pal_office_4th_floor  pal_office_7th_floor  small_house  small_office  small_warehouse
```

**Comment by saikishor** [comment]
Fixed with https://github.com/pal-robotics/pmb2_navigation/pull/3
